### ISSUE TITLE
Minimal Docker-Compose when only used w/ FileRun for editing/creating docs

### ISSUE THREAD

**Issue by zilexa** [ONLYOFFICE/Docker-CommunityServer#101]
Just wondering which services are absolutely required, when I will only access OnlyOffice via FileRun, to edit and maybe create Office documents?

For example I can leave out the Mail Server. It is however unclear to me if the mySQL database is necessary? As I will not use recent documents or stuff like that (I use FileRun to see my recent docs). 

Is it possible to only use the onlyoffice-document-server container? Or does it require the onlyoffice-community-server, even if you leave out mailserver and mySQL?

Reason why I asked, I am a home user and accidentally installed the wrong version of OnlyOffice (Integration Edition, which does not work in combination with FileRun). But, in Docker-Compose it only required this: 
```
  onlyoffice:
    image: onlyoffice/documentserver-ie:latest
    container_name: onlyoffice
    stdin_open: true
    restart: always
    links:
      - filerun
    ports:
      - "8001:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=$ONLYOFFICEJWT
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
```
(I left out the Labels section as that's only for https via Traefik)

And it "works", example document works, myip:8001 works. But Integration Edition does not work with FileRun so I need Community Edition. Just want to keep it as simple as possible for my server.
