### ISSUE TITLE
Excessive processes and memory usage

### ISSUE THREAD

**Issue by localjo** [ONLYOFFICE/Docker-CommunityServer#119]
I've installed the document server with the following in my docker-compose.yml:

```
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
```

But in an idle state, the document server container is using a lot of memory and has a lot of processes:
```
CONTAINER ID   NAME                               CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
0003326516b7   onlyoffice-document-server         101.85%   1.099GiB / 2.932GiB   37.50%    1.21kB / 0B       572MB / 153MB    157
```

Any ideas what I can do to cut down on the document server's memory usage?
