### ISSUE TITLE
Permission denied nginx and unknown error on nextcloud

### ISSUE THREAD

**Issue by julyusito** [ONLYOFFICE/Docker-CommunityServer#121]
Hi,

I've installed nextcloud and onlyoffice latest version within docker with this setup:

```
version: '3' 

services:

  db:
    image: mariadb
    hostname: nc_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file: /PATH_TO_DOCKER_VOLUMES/nextcloud-db.env
    networks:
      - internal 
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
      restart_policy:
        condition: on-failure
    volumes:
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-db/var/lib/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  

  db_backup:
    image: mariadb
    hostname: nc_db_backup
    env_file: /PATH_TO_DOCKER_VOLUMES/nextcloud-db-backup.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    volumes:
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-db/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
    - internal 

  redis:
    image: redis:alpine
    hostname: nc_redis
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
      restart_policy:
        condition: on-failure
    networks:
      - internal 
    volumes:
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-db/data:/data
      - /etc/localtime:/etc/localtime:ro

  apps:
    image: nextcloud:latest
    hostname: nextcloud
    env_file: /PATH_TO_DOCKER_VOLUMES/nextcloud-apps.env
    networks:
      - internal 
      - container_external 
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8192M
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - haproxy.frontend.rule=Host:cloud.cpp.com.co
        - haproxy.docker.network=container_external
        - haproxy.port=80 
    ports:
      - IP_HOST_DOCKER:10105:80
    depends_on:
      - db
      - db_backup
      - redis
    volumes:
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-apps/var/www/html:/var/www/html
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-apps/var/www/html/config:/var/www/html/config
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-apps/var/www/html/custom_apps:/var/www/html/custom_apps
      - /PATH_TO_DOCKER_VOLUMES/NCData/cloud:/var/www/html/data
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-apps/var/www/html/themes:/var/www/html/themes
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/www/onlyoffice/Data/certs/WildcardCPP.all.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/www/onlyoffice/Data/certs/WildcardCPP.key:/etc/ssl/private/ssl-cert-snakeoil.key
      - /etc/localtime:/etc/localtime:ro
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-apps/etc/apache2/mods-enabled/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf
    restart: unless-stopped

  cron:
    image: nextcloud:latest
    hostname: nc_cron
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
      update_config:
        delay: 15s
      restart_policy:
        condition: on-failure
    depends_on:
      - apps
    volumes:
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-apps/var/www/html:/var/www/html
      - /PATH_TO_DOCKER_VOLUMES/NCData/cloud:/var/www/html/data
    user: www-data
    networks:
      - internal 
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done
        while true; do
          php -f /var/www/html/cron.php
          sleep 5m
        done
      EOF'

  documentserver:
    image: onlyoffice/documentserver:latest
    hostname: nc_onlyoffice
    env_file: /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice.env
    networks:
      - container_external
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4096M
      update_config:
        delay: 15s
      restart_policy:
        condition: on-failure
    ports:
      - IP_HOST_DOCKER:10106:80
      - IP_HOST_DOCKER:10107:443
    depends_on:
      - apps
    volumes:
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/lib/onlyoffice:/var/lib/onlyoffice
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/www/onlyoffice/Data:/var/www/onlyoffice/Data 
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/log/onlyoffice:/var/log/onlyoffice  
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/lib/redis:/var/lib/redis
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/lib/postgresql:/var/lib/postgresql
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/www/onlyoffice/Data/certs/WildcardCPP.crt:/var/www/onlyoffice/Data/certs/tls.crt:rw
      - /PATH_TO_DOCKER_VOLUMES/nextcloud-onlyoffice/var/www/onlyoffice/Data/certs/WildcardCPP.key:/var/www/onlyoffice/Data/certs/tls.key:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

networks:
  container_external :
    external: true
  internal :
    driver: bridge
```

I'm not running any other script, just the docker setup, because it's on a NAS system

This is my setup on nextcloud:
![Captura de pantalla 2021-05-19 a la(s) 5 58 37 a  m](https://user-images.githubusercontent.com/69789966/118802563-dfc05c00-b867-11eb-96aa-8dabea6c292d.png)

All of this is behind a proxy (HAProxy):

```
backend documentserver.XXXX.com.co_ipvANY
	mode			http
	id			113
	log			global
	timeout connect		30000
	timeout server		7200000
	retries			3
	source ipv4@ usesrc clientip
	acl			existing-x-forwarded-host	req.hdr(X-Forwarded-Host) -m found
	acl			existing-x-forwarded-proto 	req.hdr(X-Forwarded-Proto) -m found
	http-request add-header X-Forwarded-Host %[req.hdr(Host)] unless existing-x-forwarded-host 
	http-request add-header X-Forwarded-Proto https unless existing-x-forwarded-proto 
	server			documentserver IP_HOST_DOCKER:10107 id 101 ssl  verify none 
```
All saves perfect on nextcloud and there is no error on logs, but when I open a file from nextcloud, throws the "Unknown error"
![Captura de pantalla 2021-05-19 a la(s) 6 06 09 a  m](https://user-images.githubusercontent.com/69789966/118802976-68d79300-b868-11eb-8c00-d0cb6cd5413b.png)

All healtcheck pass with "true" result

In the /var/log/onlyoffice/documentserver/nginx.error.log of onlyoffice show this: Permission denied
2021/05/19 05:37:19 [error] 13024#13024: *21 open() "/var/lib/onlyoffice/documentserver/App_Data/cache/files/409621677/Editor.bin" failed (13: Permission denied), client: 172.29.16.1, server: , request: "GET /cache/files/409621677/Editor.bin/Editor.bin?md5=OMlXJtxJY4iPP0pXiy64sQ&expires=1624012640&disposition=attachment&filename=Editor.bin HTTP/1.1", host: "documentserver.XXXX.com.co", referrer: "https://documentserver.XXXX.com.co/6.2.2-21/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.2.2-21&lang=es&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://XXXX.XXXX.com.co"

If I use this setup on nextcloud:
![Captura de pantalla 2021-05-19 a la(s) 6 15 56 a  m](https://user-images.githubusercontent.com/69789966/118804203-041d3800-b86a-11eb-9fad-15fae3f3a5ce.png)

There is an error on Nextcloud: Forbidden
![Captura de pantalla 2021-05-19 a la(s) 6 20 29 a  m](https://user-images.githubusercontent.com/69789966/118804480-5bbba380-b86a-11eb-9e3c-837b8111de11.png)

Please help!
