### ISSUE TITLE
Onlyoffice-mysql-server continuous restart

### ISSUE THREAD

**Issue by aaronouthier** [ONLYOFFICE/Docker-CommunityServer#161]
I have reinstalled the OS multiple times now, with no change in behavior.

I am using the docker-compose method.

The Mysql 5.7 server can’t open the error log at /var/log/mysql/error.log, which causes the mysql server to shutdown, and the container to restart. Upon restarting, the same issue.

I first encountered this issue on my working, running onlyoffice instance, after running ‘docker-compose down; docker-compose pull; docker-compose up -d’

During the pull, only the MySQL server was updated. This was about 2 weeks ago.

I will attach the relevant logs in a moment.

**Comment by aaronouthier** [comment]
[onlyoffice-mysql-server-logs.txt](https://github.com/ONLYOFFICE/Docker-CommunityServer/files/9224769/onlyoffice-mysql-server-logs.txt)

**Comment by johnny12150** [comment]
Having similar issue when use the `docker-compose` method to install.

```
2022-08-01 11:46:33+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.39-1.el7 started.
2022-08-01 11:46:33+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-08-01 11:46:33+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.39-1.el7 started.
2022-08-01 11:46:33+00:00 [Note] [Entrypoint]: Initializing database files
2022-08-01T11:46:33.430499Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2022-08-01T11:46:33.430533Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
2022-08-01T11:46:33.431769Z 0 [ERROR] Could not open file '/var/log/mysql/error.log' for error logging: No such file or directory
2022-08-01T11:46:33.431865Z 0 [ERROR] Aborting
```

**Comment by aaronouthier** [comment]
Update: I exported the docker file system and examined it. The entire /var/log/mysql folder is not present. I tried creating it, and then importing the resulting file structure, but no difference in behavior was observed.

**Comment by aaronouthier** [comment]
Changing the docker-compose line to use mysql 5.7.36 instead of just 5.7 seems to fix the issue. Note that this is on a fresh install.

**Comment by aaronouthier** [comment]
I haven’t yet created a sign-in, or gone through the web-setup procedure. I’m just going by the logs, and because docker-compose ps shows everything is up.

**Comment by Carazyda** [comment]
Hello @aaronouthier yes, we have a problem with docker-compose method (Bug 58366 in our private bugtracker). We will fix it soon.

For now i can recommend you use our installation scripts:
Workspace - https://download.onlyoffice.com/install/enterprise-install.sh

**Comment by aaronouthier** [comment]
I much prefer the simplicity of Docker-Compose, thank you. I will wait until it is fixed.

**Comment by aaronouthier** [comment]
Hello, any update on this, or ETA on a resolution using Docker-Compose?

**Comment by Carazyda** [comment]
Fixed by https://github.com/ONLYOFFICE/Docker-CommunityServer/commit/d56461d082fafd401b15d3aebfb28bd4211042a1

**Comment by unsalkorkmaz** [comment]
problem still resumes.

**Comment by aaronouthier** [comment]
I can confirm this. Began anew when reverting back to mysql 5. It was fixed when moving to mysql 8, however that introduced a different problem there.

**Comment by unsalkorkmaz** [comment]
my solution was:
Adding a volume for log folder like this;

```
version: '3'
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=deleted
    networks:
     - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - ./config/mysql/conf.d:/etc/mysql/conf.d
     - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - ./korkmaz_mysql_data:/var/lib/mysql
     - ./korkmaz_mysql_log:/var/log/mysql
```
     
and then 999 id as owner;
![Screen Shot 2022-10-05 at 02 21 24](https://user-images.githubusercontent.com/207720/193948170-f3b59319-cdfe-4123-8f7e-7f1cc6b76061.png)
