### ISSUE TITLE
MYSQL, CommunityServer, MailServer issues (Workspace on Synology NAS)

### ISSUE THREAD

**Issue by Dvalin21** [ONLYOFFICE/Docker-CommunityServer#216]
I've tried several versions from 8.0.36 to 9.0.1. Still get the same issue. After several hours of trying to trouble shoot, I discovered that with the Synology NAS I couldn't map any of the folders to the mysql folder on the host without communityserver and mailserver failing to connect to the mysql container. After discovering this, once I removed the mapping, 

Example:
```
#      - /volume1/docker/onlyoffice/mysql/conf.d:/etc/mysql/conf.d
#      - /volume1/docker/onlyoffice/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#      - /volume1/docker/onlyoffice/mysql/data:/var/lib/mysql
```
communityserver finally connected. conf.d and docker-entrypoint-initdb.d is always being ignored so whatever settings don't get applied. 

Another issue is with the CommunityServer that two of the services fail which may only fail because there are a services the fail with the MailServer. The service in the mail service fail, because of issues with MySQL. On the CS, the MailAgregator.service fails and the MailWatchdog.service fails. On the MailServer, the  OpenDKIM service fails because of the authentication protocol is not supported by the client.

Note: I know that the issue with the mysql data folder on the host being mapped is a permission issue. Same thing with the other two folders that would go in that same folder. Should I use UMASK=002 to fix this with mysql? 

Issue one
```
[Warning] [MY-013360] [Server] Plugin sha256_password reported: ''sha256_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
onlyoffice-mysql-server      | 2024-07-29T04:02:33.065370Z 89 [Warning] [MY-013360] [Server] Plugin sha256_password reported: ''sha256_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
onlyoffice-mysql-server      | 2024-07-29T04:02:33.070286Z 90 [Warning] [MY-013360] [Server] Plugin sha256_password reported: ''sha256_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead
```
Issue two
```
ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
```
Issue three
```
onlyoffice-mail-server       | Starting OpenDKIM Milter: opendkim: /etc/opendkim.conf: dsn:mysql://mail_admin:Isadmin123@onlyoffice-mysql-server/onlyoffice_mailserver/table=dkim?keycol=domain_name?datacol=id: dkimf_db_open(): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server       |                             [FAILED]
```
Issue four
```
onlyoffice-mysql-server      | mysqld: [Warning] World-writable config file '/etc/mysql/conf.d/onlyoffice.cnf' is ignored.
onlyoffice-mysql-server      | 2024-07-26T22:16:59.262871Z 0 [System] [MY-015017] [Server] MySQL Server Initialization - start.
onlyoffice-mysql-server      | 2024-07-26T22:16:59.264412Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 9.0.1) initializing of server in progress as process 80
onlyoffice-mysql-server      | 2024-07-26T22:16:59.266216Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
onlyoffice-mysql-server      | 2024-07-26T22:16:59.266221Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
onlyoffice-mysql-server      | 2024-07-26T22:16:59.266271Z 0 [ERROR] [MY-010119] [Server] Aborting
onlyoffice-mysql-server      | 2024-07-26T22:16:59.266689Z 0 [System] [MY-015018] [Server] MySQL Server Initialization - end.
onlyoffice-mysql-server      | 2024-07-26 22:17:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
onlyoffice-mysql-server      | 2024-07-26 22:17:45+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
onlyoffice-mysql-server      | 2024-07-26 22:17:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
onlyoffice-mysql-server      | 2024-07-26 22:17:45+00:00 [Note] [Entrypoint]: Initializing database files
onlyoffice-mysql-server      | mysqld: [Warning] World-writable config file '/etc/mysql/conf.d/onlyoffice.cnf' is ignored.
onlyoffice-mysql-server      | 2024-07-26T22:17:45.769218Z 0 [System] [MY-015017] [Server] MySQL Server Initialization - start.
onlyoffice-mysql-server      | 2024-07-26T22:17:45.770631Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 9.0.1) initializing of server in progress as process 80
onlyoffice-mysql-server      | 2024-07-26T22:17:45.772447Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
onlyoffice-mysql-server      | 2024-07-26T22:17:45.772452Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
onlyoffice-mysql-server      | 2024-07-26T22:17:45.772502Z 0 [ERROR] [MY-010119] [Server] Aborting
onlyoffice-mysql-server      | 2024-07-26T22:17:45.772932Z 0 [System] [MY-015018] [Server] MySQL Server Initialization - end.
onlyoffice-mysql-server exited with code 0
onlyoffice-mysql-server      | 2024-07-26 22:18:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
onlyoffice-mysql-server      | 2024-07-26 22:18:09+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
onlyoffice-mysql-server      | 2024-07-26 22:18:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
onlyoffice-mysql-server      | 2024-07-26 22:18:09+00:00 [Note] [Entrypoint]: Initializing database files
onlyoffice-mysql-server      | mysqld: [Warning] World-writable config file '/etc/mysql/conf.d/onlyoffice.cnf' is ignored.
onlyoffice-mysql-server      | 2024-07-26T22:18:09.893748Z 0 [System] [MY-015017] [Server] MySQL Server Initialization - start.
onlyoffice-mysql-server      | 2024-07-26T22:18:09.895376Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 9.0.1) initializing of server in progress as process 80
onlyoffice-mysql-server      | 2024-07-26T22:18:09.897418Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
onlyoffice-mysql-server      | 2024-07-26T22:18:09.897424Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
onlyoffice-mysql-server      | 2024-07-26T22:18:09.897475Z 0 [ERROR] [MY-010119] [Server] Aborting
onlyoffice-mysql-server      | 2024-07-26T22:18:09.897940Z 0 [System] [MY-015018] [Server] MySQL Server Initialization - end.
onlyoffice-mysql-server exited with code 0
onlyoffice-mysql-server      | 2024-07-26 22:18:31+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
onlyoffice-mysql-server      | 2024-07-26 22:18:31+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
onlyoffice-mysql-server      | 2024-07-26 22:18:31+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
onlyoffice-mysql-server      | 2024-07-26T22:18:32.384375Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
onlyoffice-mysql-server      | 2024-07-26T22:18:32.384380Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
onlyoffice-mysql-server      | 2024-07-26T22:18:32.384427Z 0 [ERROR] [MY-010119] [Server] Aborting
onlyoffice-mysql-server      | 2024-07-26T22:18:32.384427Z 0 [ERROR] [MY-010119] [Server] Aborting
onlyoffice-mysql-server      | 2024-07-26T22:18:32.384879Z 0 [System] [MY-015018] [Server] MySQL Server Initialization - end.
onlyoffice-mysql-server      | 2024-07-26T22:18:32.384879Z 0 [System] [MY-015018] [Server] MySQL Server Initialization - end.
onlyoffice-mysql-server exited with code 1
```
Issue five
```
× onlyofficeMailWatchdog.service - ONLYOFFICE MailWatchdog Service
     Loaded: loaded (/lib/systemd/system/onlyofficeMailWatchdog.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Mon 2024-07-29 05:47:40 UTC; 7min ago
    Process: 7158 ExecStart=/usr/bin/dotnet /var/www/onlyoffice/Services/MailWatchdog/ASC.Mail.Watchdog.Service.dll --urls=http://0.0.0.0:5031 --pathToConf=/etc/onlyoffice/communityserver --pathToNlogConf=/etc/onlyoffice/communityserver --log:dir=/var/log/onlyoffice/mail --log:name=mail-watchdog --ENVIRONMENT=production (code=dumped, signal=ABRT)
   Main PID: 7158 (code=dumped, signal=ABRT)
```
Issue 6
```
× onlyofficeMailAggregator.service - ONLYOFFICE MailAggregator Service
     Loaded: loaded (/lib/systemd/system/onlyofficeMailAggregator.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Mon 2024-07-29 05:47:40 UTC; 39min ago
    Process: 7183 ExecStart=/usr/bin/dotnet /var/www/onlyoffice/Services/MailAggregator/ASC.Mail.Aggregator.Service.dll --urls=http://0.0.0.0:5025 --pathToConf=/etc/onlyoffice/communityserver --pathToNlogConf=/etc/onlyoffice/communityserver --log:dir=/var/log/onlyoffice/mail --log:name=mail-aggregator --ENVIRONMENT=production (code=dumped, signal=ABRT)
   Main PID: 7183 (code=dumped, signal=ABRT)
```
Docker-compose
```
version: "3"
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:9.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=
      - TZ=America/Chicago
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    expose:
      - "3306"
      - "33060"
  #    volumes:
  #      - /volume1/docker/onlyoffice/mysql/conf.d:/etc/mysql/conf.d
  #      - /volume1/docker/onlyoffice/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #      - /volume1/docker/onlyoffice/mysql/data:/var/lib/mysql

  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:12.5.2.1848
    depends_on:
      - onlyoffice-mysql-server
      - onlyoffice-document-server
      - onlyoffice-mail-server
      - onlyoffice-elasticsearch
    environment:
      - ONLYOFFICE_CORE_MACHINEKEY=
      - TZ=America/Chicago
      - CONTROL_PANEL_PORT_80_TCP=80
      - CONTROL_PANEL_PORT_80_TCP_ADDR=onlyoffice-control-panel
      - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
      - DOCUMENT_SERVER_JWT_ENABLED=true
      - DOCUMENT_SERVER_JWT_SECRET=
      - DOCUMENT_SERVER_JWT_HEADER=AuthorizationJwt
      - MYSQL_SERVER_ROOT_PASSWORD=
      - MYSQL_SERVER_DB_NAME=onlyoffice
      - MYSQL_SERVER_HOST=onlyoffice-mysql-server
      - MYSQL_SERVER_USER=onlyoffice_user
      - MYSQL_SERVER_PASS=onlyoffice_pass
      - MAIL_SERVER_API_PORT=8081
      - MAIL_SERVER_API_HOST=onlyoffice-mail-server
      - MAIL_SERVER_DB_HOST=onlyoffice-mysql-server
      - MAIL_SERVER_DB_PORT=3306
      - MAIL_SERVER_DB_NAME=onlyoffice_mailserver
      - MAIL_SERVER_DB_USER=mail_admin
      - MAIL_SERVER_DB_PASS=
      - ELASTICSEARCH_SERVER_HOST=onlyoffice-elasticsearch
      - ELASTICSEARCH_SERVER_HTTPPORT=9200
    ports:
      - 8500:80
      - 5222:5222
      - 9443:443
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    #    cgroup: host
    volumes:
      - /volume1/docker/onlyoffice/communityserver/data:/var/www/onlyoffice/Data
      - /volume1/docker/onlyoffice/communityserver/logs:/var/log/onlyoffice
      - /volume1/docker/onlyoffice/communityserver/letsencrypt:/etc/letsencrypt
      - /volume1/docker/onlyoffice/documentserver/data:/var/www/onlyoffice/DocumentServerData
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /volume1/docker/onlyoffice/communityserver/certs:/var/www/onlyoffice/Data/certs
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver-ee:latest
    stdin_open: true
    tty: true
    restart: always
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=Jwt password
      - JWT_HEADER=AuthorizationJwt
      - TZ=America/Chicago
    expose:
      - "80"
      - "443"
    volumes:
      - /volume1/docker/onlyoffice/documentserver/data:/var/www/onlyoffice/Data
      - /volume1/docker/onlyoffice/documentserver/logs:/var/log/onlyoffice
      - /volume1/docker/onlyoffice/documentserver/fonts:/usr/share/fonts/truetype/custom
      - /volume1/docker/onlyoffice/documentserver/forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
  onlyoffice-mail-server:
    container_name: onlyoffice-mail-server
    image: onlyoffice/mailserver:1.6.74 #1.6.75 tried both
    depends_on:
      - onlyoffice-mysql-server
    hostname: houserofmanns.com
    environment:
      - MYSQL_SERVER=onlyoffice-mysql-server
      - MYSQL_SERVER_PORT=3306
      - MYSQL_ROOT_USER=mail_admin
      - MYSQL_ROOT_PASSWD=password
      - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
      - TZ=America/Chicago
    restart: always
    privileged: true
    ports:
      - 25:25
      - 143:143
      - 587:587
    stdin_open: true
    tty: true
    expose:
      - "8081"
      - "3306"
    volumes:
      - /volume1/docker/onlyoffice/mailserver/data:/var/vmail
      - /volume1/docker/onlyoffice/mailserver/certs:/etc/pki/tls/mailserver
      - /volume1/docker/onlyoffice/mailserver/log:/var/log
  onlyoffice-control-panel:
    container_name: onlyoffice-control-panel
    depends_on:
      - onlyoffice-document-server
      - onlyoffice-mail-server
      - onlyoffice-community-server
    image: onlyoffice/controlpanel:latest
    environment:
      - ONLYOFFICE_CORE_MACHINEKEY=openssl
    expose:
      - "80"
      - "443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/onlyoffice/controlpanel/data:/var/www/onlyoffice/Data
      - /volume1/docker/onlyoffice/controlpanel/log:/var/log/onlyoffice
    stdin_open: true
    tty: true
  onlyoffice-elasticsearch:
    # https://hub.docker.com/r/onlyoffice/elasticsearch/tags 
    image: onlyoffice/elasticsearch:7.16.3
    container_name: onlyoffice-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true
      - indices.fielddata.cache.size=30%
      - indices.memory.index_buffer_size=30%
      - ingest.geoip.downloader.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - /volume1/docker/onlyoffice/elasticsearch/data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
networks:
  onlyoffice:
    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: ipv4
        gateway: ipv4
      - subnet: ipv6
        gateway: ipv6
```

**Comment by Dvalin21** [comment]
Update:   
 So I used umask 022 which actually allowed for mysql to read the conf.d and the docker-endpoint folder. However there keeps being the following error.

346ef7a540b1.err
```
2024-07-30T23:23:27.226490Z 0 [System] [MY-015015] [Server] MySQL Server - start.
2024-07-30T23:23:28.078347Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 9.0.1) starting as process 131
2024-07-30T23:23:29.166214Z 0 [Warning] [MY-000054] [Server] World-writable config file '/var/lib/mysql/auto.cnf' is ignored.
2024-07-30T23:23:29.166375Z 0 [Warning] [MY-010107] [Server] World-writable config file '/var/lib/mysql/auto.cnf' has been removed.
2024-07-30T23:23:29.167075Z 0 [Warning] [MY-010075] [Server] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: ba88e4d3-4eca-11ef-8a9e-0242c0a83003.
2024-07-30T23:23:30.155263Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2024-07-30T23:24:32.806798Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2024-07-30T23:25:13.987100Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2024-07-30T23:25:13.987149Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2024-07-30T23:25:14.139612Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2024-07-30T23:25:16.325069Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
2024-07-30T23:25:16.325133Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '9.0.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
```
Community Server nginx error
```
2024/07/31 02:46:09 [crit] 5952#5952: *1807 connect() to unix:/var/run/onlyoffice/onlyoffice.socket failed (2: No such file or directory) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /TenantLogo.ashx?logotype=2&general=false HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "10.0.0.5:8500", referrer: "http://10.0.0.5:8500/"
2024/07/31 02:46:09 [crit] 5952#5952: *1807 connect() to unix:/var/run/onlyoffice/onlyoffice.socket failed (2: No such file or directory) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /TenantLogo.ashx?logotype=3 HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "10.0.0.5:8500", referrer: "http://10.0.0.5:8500/"
```
Community Server mailserver cleaner storage error log
```
2024-07-31 00:37:17,853 ERROR [41] ASC.Mail.Cleaner - Timer -> WorkTimerElapsed. Exception:
Autofac.Core.DependencyResolutionException: An exception was thrown while activating ASC.Mail.Core.Engine.MailboxEngine -> ASC.Core.TenantManager -> ASC.Core.Caching.CachedTenantService -> ASC.Core.Data.DbTenantService -> λ:Microsoft.EntityFrameworkCore.IDbContextFactory`1[[ASC.Core.Common.EF.Context.TenantDbContext, ASC.Core.Common, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null]] -> Microsoft.EntityFrameworkCore.Internal.DbContextPool`1[[ASC.Core.Common.EF.Context.TenantDbContext, ASC.Core.Common, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null]] -> λ:Microsoft.EntityFrameworkCore.DbContextOptions`1[[ASC.Core.Common.EF.Context.TenantDbContext, ASC.Core.Common, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null]].
 ---> MySqlConnector.MySqlException (0x80004005): Access denied for user 'onlyoffice_user'@'192.168.48.6' (using password: YES)
   at MySqlConnector.Core.ServerSession.SendEncryptedPasswordAsync(AuthenticationMethodSwitchRequestPayload switchRequest, String rsaPublicKey, String password, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 834
   at MySqlConnector.Core.ServerSession.SwitchAuthenticationAsync(ConnectionSettings cs, String password, PayloadData payload, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 747
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 573
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 403
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 408
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 98
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 128
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 929
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 423
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 382
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at ASC.Core.Common.EF.InstallerOptionsAction.OptionsAction(IServiceProvider sp, DbContextOptionsBuilder optionsBuilder)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass6_0`1.<AddPoolingOptions>b__0(IServiceProvider sp, DbContextOptionsBuilder ob)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.<>c__DisplayClass3_0.<Register>b__0(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
```

**Comment by Carazyda** [comment]
Hello @Dvalin21 We recommend using version 8.0.29 of the mysql docker container. We do not guarantee stable operation of Workspace with other versions. In the next releases, we will update the supported version of mysql for docker.

**Comment by Dvalin21** [comment]
> Hello @Dvalin21 We recommend using version 8.0.29 of the mysql docker container. We do not guarantee stable operation of Workspace with other versions. In the next releases, we will update the supported version of mysql for docker.

Thanks for your response. I did discover that 8.0.29 is the only one that works. So this part is fixed for me. The only thing now is trying to get communityserver from failing. Which version do you recommend using?

**Comment by Dvalin21** [comment]
Update: Switched community server to 12.5.2.1848. Its still doing the same as the latest version. It keeps failing the mailwatchdog and the other. Also, getting a access denied when trying to connect to the database user with mysql
```
2024/07/31 02:25:07	stdout	ERROR 1045 (28000): Access denied for user 'onlyoffice_user'@'192.168.48.3' (using password: YES)
2024/07/31 02:25:07	stdout	mysql: [Warning] Using a password on the command line interface can be insecure.
2024/07/31 02:25:07	stdout	++ mysql --silent --skip-column-names -h onlyoffice-mysql-server -P 3306 -u onlyoffice_user '--password=password' -D onlyoffice -e 'TRUNCATE webstudio_index'
2024/07/31 02:25:07	stdout	+ '[' '' == opt_ignore_db_name ']'
```

**Comment by Dvalin21** [comment]
> Hello @Dvalin21 We recommend using version 8.0.29 of the mysql docker container. We do not guarantee stable operation of Workspace with other versions. In the next releases, we will update the supported version of mysql for docker.

So I got it all to install and work. Ill share my docker-compose, but why is a lic file still required for the community edition?

```
version: "3"
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    networks:
      onlyoffice:
        ipv4_address: 192.168.48.2
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=
      - TZ=America/Chicago
      - UMASK=022
#      - UMASK_DIR=755
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    expose:
      - "3306"
      - "33060"
    volumes:
      - /volume1/docker/onlyoffice/mysql/conf.d:/etc/mysql/conf.d
      - /volume1/docker/onlyoffice/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /volume1/docker/onlyoffice/mysql/data:/var/lib/mysql

  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    networks:
      onlyoffice:
        ipv4_address: 192.168.48.3
    image: onlyoffice/communityserver:12.5.2.1848
    depends_on:
      - onlyoffice-mysql-server
      - onlyoffice-document-server
      - onlyoffice-mail-server
      - onlyoffice-elasticsearch
    environment:
      - ONLYOFFICE_CORE_MACHINEKEY=
      - TZ=America/Chicago
      - CONTROL_PANEL_PORT_80_TCP=80
      - CONTROL_PANEL_PORT_80_TCP_ADDR=onlyoffice-control-panel
      - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
      - DOCUMENT_SERVER_JWT_ENABLED=true
      - DOCUMENT_SERVER_JWT_SECRET=
      - DOCUMENT_SERVER_JWT_HEADER=AuthorizationJwt
      - MYSQL_SERVER_ROOT_PASSWORD=
      - MYSQL_SERVER_DB_NAME=onlyoffice
      - MYSQL_SERVER_HOST=onlyoffice-mysql-server
      - MYSQL_SERVER_USER=onlyoffice_user
      - MYSQL_SERVER_PASS=onlyoffice_pass
      - MAIL_SERVER_API_PORT=8081
      - MAIL_SERVER_API_HOST=onlyoffice-mail-server
      - MAIL_SERVER_DB_HOST=onlyoffice-mysql-server
      - MAIL_SERVER_DB_PORT=3306
      - MAIL_SERVER_DB_NAME=onlyoffice_mailserver
      - MAIL_SERVER_DB_USER=mail_admin
      - MAIL_SERVER_DB_PASS=Isadmin123
      - ELASTICSEARCH_SERVER_HOST=onlyoffice-elasticsearch
      - ELASTICSEARCH_SERVER_HTTPPORT=9200
    ports:
      - 8500:80
      - 5222:5222
      - 9443:443
    expose:
      - "9865"
      - "9888" 
      - "9866" 
      - "9871" 
      - "9882" 
      - "5280"
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    #    cgroup: host
    volumes:
      - /volume1/docker/onlyoffice/communityserver/data:/var/www/onlyoffice/Data
      - /volume1/docker/onlyoffice/communityserver/logs:/var/log/onlyoffice
      - /volume1/docker/onlyoffice/communityserver/letsencrypt:/etc/letsencrypt
      - /volume1/docker/onlyoffice/documentserver/data:/var/www/onlyoffice/DocumentServerData
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /volume1/docker/onlyoffice/communityserver/certs:/var/www/onlyoffice/Data/certs

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    networks:
      onlyoffice:
        ipv4_address: 192.168.48.4
    image: onlyoffice/documentserver-ee:latest
    stdin_open: true
    tty: true
    restart: always
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=TGCrx6eUsG2Ww45RLwpRLFKvDiYbeDjL
      - JWT_HEADER=AuthorizationJwt
      - TZ=America/Chicago
    expose:
      - "80"
      - "443"
    volumes:
      - /volume1/docker/onlyoffice/documentserver/data:/var/www/onlyoffice/Data
      - /volume1/docker/onlyoffice/documentserver/logs:/var/log/onlyoffice
      - /volume1/docker/onlyoffice/documentserver/fonts:/usr/share/fonts/truetype/custom
      - /volume1/docker/onlyoffice/documentserver/forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten

  onlyoffice-mail-server:
    container_name: onlyoffice-mail-server
    networks:
      onlyoffice:
        ipv4_address: 192.168.48.5
        ipv6_address: 2600:1700:b730::5
    image: onlyoffice/mailserver:1.6.75
    depends_on:
      - onlyoffice-mysql-server
    hostname: houserofmanns.com
    environment:
      - MYSQL_SERVER=onlyoffice-mysql-server
      - MYSQL_SERVER_PORT=3306
      - MYSQL_ROOT_USER=mail_admin
      - MYSQL_ROOT_PASSWD=Isadmin123
      - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
      - TZ=America/Chicago
    restart: always
    privileged: true
    ports:
      - 25:25
      - 143:143
      - 587:587
    stdin_open: true
    tty: true
    expose:
      - "8081"
      - "3306"
    volumes:
      - /volume1/docker/onlyoffice/mailserver/data:/var/vmail
      - /volume1/docker/onlyoffice/mailserver/certs:/etc/pki/tls/mailserver
      - /volume1/docker/onlyoffice/mailserver/log:/var/log

  onlyoffice-control-panel:
    container_name: onlyoffice-control-panel
    networks:
      onlyoffice:
        ipv4_address: 192.168.48.6
    depends_on:
      - onlyoffice-document-server
      - onlyoffice-mail-server
      - onlyoffice-community-server
    image: onlyoffice/controlpanel:latest
    environment:
      - ONLYOFFICE_CORE_MACHINEKEY=
    expose:
      - "80"
      - "443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/onlyoffice/controlpanel/data:/var/www/onlyoffice/Data
      - /volume1/docker/onlyoffice/controlpanel/log:/var/log/onlyoffice
    stdin_open: true
    tty: true

  onlyoffice-elasticsearch:
    # https://hub.docker.com/r/onlyoffice/elasticsearch/tags 
    image: onlyoffice/elasticsearch:7.16.3
    container_name: onlyoffice-elasticsearch
    networks:
      onlyoffice:
        ipv4_address: 192.168.48.7
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true
      - indices.fielddata.cache.size=30%
      - indices.memory.index_buffer_size=30%
      - ingest.geoip.downloader.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - /volume1/docker/onlyoffice/elasticsearch/data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
networks:
  onlyoffice:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 192.168.48.0/24
        gateway: 192.168.48.1
      - subnet:  
        gateway:
```
