### ISSUE TITLE
Running CommunityServer with DocumentServer on different port

### ISSUE THREAD

**Issue by UFOMelkor** [ONLYOFFICE/Docker-CommunityServer#25]
Hi,

we try to setup the Community Server together with the Document Server on a different port.
This is our `docker-compose.yml`:
```yml
version: '3.0'
services:
    onlyoffice-community-server:
        container_name: onlyoffice-community-server
        image: onlyoffice/communityserver:latest
        depends_on:
         - onlyoffice-document-server
        environment:
         - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
        networks:
         - onlyoffice
        ports:
         - '8080:80'
         - '444:443'
         - '5222:5222'
        stdin_open: true
        tty: true
        restart: always
        volumes:
         - ./community_mysql:/var/lib/mysql
         - ./community_data:/var/www/onlyoffice/Data
         - ./community_log:/var/log/onlyoffice
         - ./document_data:/var/www/onlyoffice/DocumentServerData
         - ./certs:/var/www/onlyoffice/Data/certs
    onlyoffice-document-server:
        container_name: onlyoffice-document-server
        image: onlyoffice/documentserver:latest
        stdin_open: true
        tty: true
        restart: always
        networks:
            - onlyoffice
        expose:
            - '80'
            - '443'
        volumes:
             - ./document_data:/var/www/onlyoffice/Data
             - ./document_fonts:/usr/share/fonts/truetype/custom
             - ./document_log:/var/log/onlyoffice
networks:
    onlyoffice:
        driver: 'bridge'
```
After executing `docker-compose up` the server are starting, we can insert our password and chosen language and timezone. But when we try to open a document we get a connection refused from:
`/2017-06-09-10-21/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2017-06-09-10-21&lang=en-US&customer=ONLYOFFICE&frameEditorId=iframeEditor` which is forwarded from
`:8080/2017-06-09-10-21/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2017-06-09-10-21&lang=en-US&customer=ONLYOFFICE&frameEditorId=iframeEditor` (different port).

Is using another port not supported yet or do we miss anything?
